name: Deploy to S3 and Amplify

on:
  push:
    branches:
      - main
      - ajay/ps-integration

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3 using AWS CLI
        run: |
          aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude ".gitignore" \
            --exclude "*.md" \
            --exclude ".DS_Store"

      - name: Trigger Amplify Deploy
        run: |
          aws amplify start-deployment \
            --app-id ${{ secrets.AMPLIFY_APP_ID }} \
            --branch-name ${{ secrets.AMPLIFY_BRANCH_NAME }} \
            --source-url s3://${{ secrets.AWS_S3_BUCKET }}
